<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="RustEarthSyncScript.cs" />
    <ProjectReference Include="../../src/RustEngine.Interop/RustEngine.Interop.csproj" />
    <PackageReference Include="Stride.Engine" Version="4.3.0.2507" />
    <PackageReference Include="Stride.Input" Version="4.3.0.2507" />
  </ItemGroup>
</Project>
